### ISSUE TITLE
Another syntax error detected

### ISSUE THREAD

**Issue by vekuda** [ssemenova/tidal-spotify-converter#3]
I have cloned the new repo, but this time I got a new error after `python script.py`:

```
File "script.py", line 138
    if playlist['name'] not in tidal_oldplaylists:
                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

Do you suggest that I should use another terminal to use this repository?

**Comment by nchiarappa** [comment]
Just replace the tab with spaces (or vice versa) at line 138

**Comment by ssemenova** [comment]
Could be your IDE/text editor converting tabs to spaces, or vice versa. I'd just replace them all to whatever you usually use.
