### ISSUE TITLE
Tidal ID obtaining method no longer working.

### ISSUE THREAD

**Issue by MacbethRene** [ssemenova/tidal-spotify-converter#4]
It looks like Tidal for web has changed, are you a re no longer able to click in your profile.
Any suggestion to find it?

**Comment by nchiarappa** [comment]
I'm using Fiddler in order to capture HTTPS traffic. In this way you can see the tidal account ID in the URL. 
https://www.telerik.com/download/fiddler

**Comment by ssemenova** [comment]
Looks like Tidal changed a bunch of their API endpoints? My URL to create a playlist is also not working anymore. I can look into this in a little bit but feel free to open a PR if you can a new URL working.

**Comment by ssemenova** [comment]
Ah, if you're comfortable with chrome or firefox developer tools, you can go to the network pane and look at the traffic, as @nchiarappa is doing. Here's what it looks like in firefox:

<img width="1105" alt="screen shot 2018-11-15 at 12 04 52 pm" src="https://user-images.githubusercontent.com/6182097/48568992-b2794880-e8ce-11e8-90a3-bd299084aa1d.png">

You can see my ID in the top right, under request URL.
